spring:
  application:
    name: demo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  threads: # Cấu hình thread pool cho Spring Boot
    virtual: # Sử dụng virtual threads (Project Loom) nếu đang chạy trên Java 19+
      enabled: true # Kích hoạt virtual threads
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # Tên lớp driver cho MySQL
  jpa:
    hibernate:
      ddl-auto: none  # Tùy chọn: none (Không làm gì), validate (Chỉ kiểm tra), update (Cập nhật), create (Tạo), create-drop (Tạo và xóa khi đóng ứng dụng)
  flyway:
     enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ""          # để trống nếu không có password
      timeout: 2000ms       # connection timeout
      lettuce:
        pool:
          max-active: 10    # max connection trong pool
          max-idle: 5
          min-idle: 1
          max-wait: 1000ms  # thời gian chờ lấy connection

cache:
  type: redis
  redis:
    time-to-live: 300000  # TTL mặc định = 5 phút (ms)
    cache-null-values: false

# JWT config
app:
  cors:
    allowed-origins: "*"
  jwt:
    secret: ""
    expiration: 300000
    refresh_expiration: 1800000 # 30 phút (milliseconds)

server:
  port: 8080

firebase:
  service-account:
    enabled: false
    path: classpath:firebase-service-account.json
